### ISSUE TITLE
Soundscape Proposal

### ISSUE THREAD

**Issue by benmiller314** [pitt-cdm/miller2019spring#4]
**Write a brief proposal for your soundscape narrative project. What _place_ or _environment_ will you try to represent? What _story_ will you try to tell – or, at least, what is the premise (starting point) of that story?**

See the full range of thought-questions in the [assignment prompt](https://github.com/pitt-cdm/soundscape-prompt) for brainstorming strategies.

NB: I am asking you to include a **prospective assets list**, i.e. a table of the sounds you think you'll need and where you might be able to source them. You can choose to include that assets list here or place it as a file in your repository, to more easily track changes. 

Either way, **please include a link here to your soundscape repository**, making it easier to find when we get to group work.

**Comment by abrous** [comment]
https://github.com/pitt-cdm/soundscape--abrous/tree/master

My proposal is to do a video about someone missing the PittCat busses. The place or environment will hopefully be a snowy or rainy day and take place on Pitt campus near any bus station. I want to use the sounds of the bus coming and going, doors opening/closing, maybe the alert on a cell phone that the bus is almost at the stop, someone yelling wait even though the bus did not. My basic list is attached in the repository!

**Comment by tessasayers** [comment]
https://github.com/pitt-cdm/soundscape--tessasayers/tree/master

For my soundscape project, I would like to tell the stories of the final minutes of a Pitt basketball game. It will be based at the Petersen Events Center. The soundscape will start with assets such as music playing during a timeout, and then Pitt getting the ball, dribbling down the court, getting fouled and the ref blowing his whistle. Then it will get silent as the player steps to the line while he shoots his foul shots, making the shot and the crowd going crazy. And then ending with the band playing and include sound clips from a post-game press conference.

**Comment by jennyaimei120** [comment]
https://github.com/pitt-cdm/soundscape--jennyaimei120/tree/master

my proposal for the soundscape project is going to be me going throughout my day. You will be able to follow me through my schedule, and essentially be able to tell what I am doing. I will have some voices included, using my friends during normal conversations throughout the day. Some things in the soundscape may be just from my own leisure time. With my last soundscape project, all we really had to do was write down directions and go out and listen to what you hear on that walk. With this one we are able to make our own, which will be fun.

**Comment by christyh310** [comment]
https://github.com/pitt-cdm/soundscape--christyh310/tree/master

For my soundscape project, I will set up a children's/elementary playground scene, and contrast this with different words (a poem) from me and those I interview (response to questions I ask). The scene will build from ambient noise, and go through different parts of the playground, making sure the listeners know where they are and possibly drawing on memories of those places/activities. Then, potentially with recess being over, or perhaps a jarring silence (near a certain part of the poem), I want to highlight certain ways we may not give kids dignity that they deserve.

**Comment by laurasosovicka** [comment]
For my soundscape, I'm going to be following my roommate throughout her day when she studies and does homework. The soundscape will start with her alarm clock waking her up, then a trip to Starbucks for a caffeine fix, then typing as she does her work. Next, you'll hear pen clicking as she writes down information along with flipping her notebook. There will be a brief moment of silence before you hear a microwave beeping and food coming out of it. Then the sounds of a shower running will end the soundscape as it fades into the background.

**Comment by esc37** [comment]
https://github.com/pitt-cdm/soundscape--esc37
For my soundscape project, I am going to do this from a bystander's perspective. The bystander will be walking to a coffee shop with a friend to do homework. As they are walking along the street, someone ends up collapsing in cardiac arrest. The bystander ends up doing CPR while the friend calls 911. They stay on scene until the ambulance arrives, then continue their walk to the coffee shop.

**Comment by bcy5** [comment]
https://github.com/pitt-cdm/soundscape--bcy5

For my soundscape project, I want to do a short story about a hero in a role-playing game, in the perspective of that hero. He will face all sorts of dangers and challenges as he traverses into an unknown territory. 
For this story, I think I will need sound effects such as metals clanging together to represent the weapon that the hero uses, and sounds of monsters and other inhuman beings that the hero might encounter throughout his journey!

**Comment by mpalko** [comment]
https://github.com/pitt-cdm/soundscape--mpalko

For my soundscape project, I was trying to think of something creative. Originally, I was just going to ask people what I think love is, and I think I still want to do that. But I also want to overlay what daily life is like for me and other people. I'll record myself at a coffee shop, and painting, and talking with friends, and etc. But the point is that I am trying to represent is that love is not just a feeling you can explain but it is also within what you like to do in your life. I really like to read, and paint and so that's why those sounds are incorporated.

**Comment by jfrank1120** [comment]
https://github.com/pitt-cdm/soundscape--jfrank1120

For my SoundScape project I am planning on following the day in the life of a grounds crew worker at Pitt. From the morning getting to campus and walking around leaf blowing, mowing grass, sweeping areas, etc. There will then be a lunch break where the listener can hear the worker crumpling papers, chewing on food, hearing the conversations of those around him. This will then follow more portions of working during the rest of the day and then end with the sound of them getting back in their car and the door shutting.

**Comment by tyllerbarner** [comment]
https://github.com/pitt-cdm/soundscape--tyllerbarner

For my soundscape project, I plan to do my project around the coffee carts on Pitt's campus. I want to either just include or focus on my friend who works at various coffee carts depending on the day. I would like to include the sounds of the espresso machine, coffee being poured, and interactions between my friend and her customers. I would like the project to start with her saying "Hi, how are you doing" and then progress throughout a "regular shift" and then end on "have a nice day."

**Comment by eaj34** [comment]
https://github.com/pitt-cdm/soundscape--eaj34

My soundscape project is going to be a narrative following a girl who tries to do her daily routine but is constantly interrupted by texts and calls from an unknown number. I was going to record sounds in my room, on the street, and in some stores. The day would start with her waking up, and then eventually getting the first text and her reaction. Her day would continue and then eventually asking her friends if they know the number, in which they reply that they don't. The sound will end with a mystery and a cliff hanger, keeping the audience on their toes. Sounds will include the notification pings of the messages, voices of the woman, street noise, rain, etc.

**Comment by dashn98** [comment]
https://github.com/pitt-cdm/soundscape--dashn98
For my soundscape project I want to make my story about a tap dancer. I would like the story to lapse over a long period of time by first having some repetitive sounds of driving to a tap practice, a teacher saying “5,6,7,8”, the sounds of tap dancing and some mistakes in the tap sounds, possibly some music in the background and the murmur between dancers after class. I then would like it to transition to the night of the show, the sounds would include the sounds of dancers talking in the dressing room, the sounds of hairspray and deep breaths. The end would include the sound of the lights clicking on, the music starting, louder this time so you know it is the performance, and a portion of a tap dance and end in cheers from the audience, cameras clicking and a sigh of relief from the dancer as she leaves the stage.

**Comment by ghost** [comment]
https://github.com/pitt-cdm/soundscape--stanickld

My proposal for the soundscape project will be me going throughout my day. Depending on whether day of the week it is (MWF or T/Th), you will be able to hear me interact with my teachers and peers during my different classes. You will also be able to hear some of my rehearsals for the play I am sound designing and cast in here at the University of Pittsburgh. I have never done a soundscape project before, but I do have some limited sound design experience so I think this will be a fun project.

**Comment by jlt118** [comment]
For my soundscape project, I would like to do a progression of life. I'd start at infancy and sounds associated with it progressing through the life stages. I think I want to do a heartbeat in the background of the other sounds. Im planning on having the beginning and end sound similar to show the cyclical pattern.

**Comment by ZAR17** [comment]
https://github.com/pitt-cdm/soundscape--ZAR17

I plan on doing the sounds of studying. I spend a lot of my time in David Lawrence computer lab either studying or doing homework. The soundscape will include basic noises that come from computers, keyboards, a mouse, the music I listen to, overhearing other people talking, walking, getting water, etc. I've came up with a narrative and have over 20 unique sounds I plan on recording as well as ideas for how to meet the criteria of 4 sounds playing simultaneously.

**Comment by jlherrle** [comment]
For my soundscape project I want to focus on the emotion of happiness. I would like to focus on the what happiness means to people specifically through sounds. I feel like this will be very interesting to get peoples opinions on what all makes people happy and what that may sound like to them. My main plan is to show that happiness isn't the same for everybody and that happiness means something different to everybody 

https://github.com/pitt-cdm/soundscape--jlherrle

**Comment by AnthonyCapretto** [comment]
https://github.com/pitt-cdm/soundscape--AnthonyCapretto.git
For my soundscape project I want to focus on recording the world around me as I commute to school. I ended up taking the incline, subway, and the bus everyday, and I feel like if I effectively record each I can convey the idea that I'm going on a journey. I don't want to really be heard much in the story; I want the listener to picture themselves traveling through a bustling city rather than picturing me.

**Comment by Aba430** [comment]
https://github.com/pitt-cdm/soundscape--Aba430.git
I would like to focus on the buses that pass through Oakland and the sounds they make as they pick up and drop off passengers. I also want to capture the sounds passengers create as they board and depart the buses, in addition to the sounds the other vehicles make as they pass by. I'm hoping to capture the sounds of sirens and honking horns as well. I want the sound of each bus stopping to anchor the piece and demonstrate how buses are more than just a vessel in Pittsburgh. Although the public transportation system can be frustrating at times, the buses are truly the backbone of the city.
