### ISSUE TITLE
Happiness

### ISSUE THREAD

**Issue by jlherrle** [pitt-cdm/miller2019spring#7]
What is happiness? 

I have always wondered what makes people the happiest. When you’re walking down the street and you see someone smiling. Is it because its a beautiful day out and there is not a cloud in the sky? Is it because they just got left class after taking a test feeling like they nailed it? 

When I first started my project I was focusing a lot of my time on interviewing people. I thought that I wanted to base my whole project on interviews and hearing what people had to say when I asked them what happiness was to them. After conducting my interviews it hit me that maybe I should express happiness not only by interviews by but sounds. This is when i decided to search for sounds that make people happy. 

As I mentioned previously, I wanted to collect sounds as well as interview people on what happiness is to them. Out of the five people I interviewed, I added 3 of their answers into the project. I selected their interviews because I felt like their answers were all very different. One girl said that happiness to her is when she gets an email saying that her class is cancelled. Another girl told me that happiness to her is being with her friends and family. When I was interviewing people it came to my attention how everybody has different things that make them happy. The last I interviewed mentioned to me that happiness to her is a sound. She told me that when she is laying on the beach, feeling the sun radiating off of her skin, happiness to her is hearing the waves crashing and the seagulls. That is why I selected a sound of seagulls and a sound of waves crashing as 2 of the 10 sounds in my project. When imported those sounds into my project I decided that it would be the perfect opportunity to overlap those noises. 

Here is a picture showing the two sounds that overlap in my project: 

<img width="1440" alt="screen shot 2019-02-03 at 10 20 50 pm" src="https://user-images.githubusercontent.com/46493137/52189453-b39f7f00-2806-11e9-9e36-73e2a18d109a.png">
<img width="1440" alt="screen shot 2019-02-03 at 10 20 38 pm" src="https://user-images.githubusercontent.com/46493137/52189457-b8643300-2806-11e9-8378-238a11a0f0c6.png">

It wasn’t easy for me to locate a lot of the sounds I wanted to find. The sounds that I were able to locate on freesound were not able to truly capture the noises and how they could make people happy. One of my audio clips is of my friends and I laughing. To me happiness is laughter and being with my friends. It was important that since my happiness is laughing, that I recorded my own audio of being with my friends joking around and having a good time. Collecting an audio clip from freesound of a group of girls laughing would not be the same as having my own laughter as well as my friends as a part of this project. I took a lot of the constructive criticism I received from classmates to help me find sounds that would work best for my project. 

The picture below gave me a lot of awesome ideas: 

![img_3115](https://user-images.githubusercontent.com/46493137/52189491-d92c8880-2806-11e9-9b2a-5026ed62318a.jpeg)

I truly hope that people enjoy my project and that after listening people will sit back and ask themselves what happiness is to them. Are they able to relate to the answers of the people I interviewed? Does the dog barking make them just as happy as it makes me? I want my project to create conversations between people and themselves.

**Comment by benmiller314** [comment]
Already copied into the main [soundscape reflection](https://github.com/pitt-cdm/miller2019spring/issues/2#issuecomment-460124882) thread; closing.
